version: "2"
services:
    node:
        build: .
        user: node
        working_dir: /home/node/app
        env_file: .env
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules
        restart: always
        depends_on:
            - postgres
        command: "npm run start"
    postgres:
        restart: always
        image: postgres:9.6.8-alpine
        expose:
            - "5432"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=shizoid
            - POSTGRES_PASSWORD=shizoid
            - POSTGRES_DB=shizoid
        volumes:
            - postgresql-volume:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d/
volumes:
    postgresql-volume:
        driver: 'local'
